apiVersion: apps/v1
kind: Deployment
metadata:
  name: myubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template: 
    metadata:
      labels:
        app: ubuntu
    spec: 
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        command: ["sleep", "14400"] #Let this container survive for 4 hours
      nodeSelector:
        handson: myubuntu
    
