apiVersion: v1
kind: LimitRange
metadata: 
  name: cpu-mem-limit-range
spec:
  limits:
  - default:
      cpu: 0.5
      memory: 128Mi
    defaultRequest:
      cpu: 0.25
      memory: 64Mi
    type: Container
     
