apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: localhost:5000/antonio/test-job-v1
            args:
            - /bin/sh
            - -c
            - date; echo H123213ernet12321er
          restartPolicy: OnFailure